const fs = require('fs');
const assert = require('assert');
const source = fs.readFileSync('js/super_admin/audit_logs.js', 'utf8');
const listeners = {};
const body = {innerHTML:'',addEventListener:(type,cb)=>listeners[type]=cb};
const fields = {children:[],replaceChildren(){this.children=[]},append(...nodes){this.children.push(...nodes)}};
const modal = {addEventListener(){},showModal(){this.open=true}};
const document = {getElementById:id=>({auditTableBody:body,auditDetailDialog:modal,auditDetailFields:fields}[id]),createElement:tag=>({tag,textContent:''})};
const setup = source.slice(source.indexOf('  const auditTableBody ='), source.indexOf('  const searchInput ='));
const render = source.slice(source.indexOf('  function renderTable('), source.indexOf('  // Render Pagination Controls'));
const run = new Function('document','escapeHtml','formatRoleBadge','formatActionBadge','formatDate', setup+render+';return renderTable;');
const escape = v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const renderTable = run(document,escape,escape,escape,escape);
const details = '<script>unsafe</script>\n'+'Full information '.repeat(30);
const row = {id:1,id_number:'2026-0001',full_name:'Test User',username:'test.user01',role:'admin',action:'Edit Account',details,time_in:'2026-09-13 10:00:00',time_out:null};
renderTable([row]);
assert(body.innerHTML.includes('data-view-log="1"'));
assert(body.innerHTML.includes(escape(details)));
assert(!body.innerHTML.includes(details));
assert(!body.innerHTML.includes('<script>'));
listeners.click({target:{closest:()=>({dataset:{viewLog:'1'}})}});
assert(modal.open);
assert(fields.children.some(node=>node.textContent===details));
assert.strictEqual(fields.children.length,Object.keys(row).length*2);
renderTable([]);
assert(body.innerHTML.includes('colspan="10"'));
const accountSource=fs.readFileSync('js/account_management.js','utf8');
const start=accountSource.indexOf("        editForm.elements.role.querySelectorAll('option')");
const end=accountSource.indexOf('        editForm.elements.role.value = detail.role;',start);
const options=['user','admin','superadmin'].map(value=>({value}));
const setOptions=new Function('editForm','detail',accountSource.slice(start,end));
const editForm={elements:{role:{querySelectorAll:()=>options}}};
setOptions(editForm,{role:'user'});
assert.deepStrictEqual(options.filter(o=>!o.hidden).map(o=>o.value),['user','admin']);
setOptions(editForm,{role:'admin'});
assert(options.every(o=>!o.hidden && !o.disabled));
console.log('PASS: full audit details, complete safe modal content, empty-state columns, and role dropdown choices.');
